// frontend-persuratan/src/components/layout/KalenderBulananModal.tsx
'use client';

import React, { useState, useMemo } from 'react';
import Swal from 'sweetalert2';
import { useGetLibur, useAddLibur, useDeleteLibur } from '@/features/libur/api';
import { useAuthStore } from '@/store/useAuthStore';

interface KalenderBulananModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const monthsList = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
];

export function KalenderBulananModal({ isOpen, onClose }: KalenderBulananModalProps) {
  const { user } = useAuthStore();
  const isAdmin = user?.role === 'ADMIN';

  const now = useMemo(() => new Date(), []);
  const [currentMonth, setCurrentMonth] = useState(now.getMonth());
  const [currentYear, setCurrentYear] = useState(now.getFullYear());
  const [viewMode, setViewMode] = useState<'bulanan' | 'mingguan'>('bulanan');
  const [selectedDateStr, setSelectedDateStr] = useState<string | null>(null);

  const { data: liburData } = useGetLibur();
  const { mutateAsync: addLibur } = useAddLibur();
  const { mutateAsync: deleteLibur } = useDeleteLibur();

  const holidaysDict = useMemo(() => {
    const dict: Record<string, string> = {};
    if (liburData) {
      liburData.forEach(l => {
        const dStr = new Date(l.tanggal).toISOString().split('T')[0];
        dict[dStr] = l.keterangan;
      });
    }
    return dict;
  }, [liburData]);

  const activeSelected = useMemo(() => {
    let target = selectedDateStr;
    if (!target) {
      target = now.toISOString().split('T')[0];
    }
    
    const [y, m, d] = target.split('-');
    const dateObj = new Date(Number(y), Number(m) - 1, Number(d));
    const dayOfWeek = dateObj.getDay();
    
    return {
      dateString: target,
      dateObj: dateObj,
      dayNum: dateObj.getDate(),
      dayOfWeek: dayOfWeek,
      isWeekend: dayOfWeek === 0 || dayOfWeek === 6,
      holidayName: holidaysDict[target] || '',
      isHoliday: !!holidaysDict[target],
      isToday: target === now.toISOString().split('T')[0],
    };
  }, [selectedDateStr, holidaysDict, now]);

  const calendarDays = useMemo(() => {
    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
    const days = [];
    const todayStr = now.toISOString().split('T')[0];

    for (let d = 1; d <= daysInMonth; d++) {
      const dateObj = new Date(currentYear, currentMonth, d);
      const y = dateObj.getFullYear();
      const m = String(dateObj.getMonth() + 1).padStart(2, '0');
      const dayPad = String(d).padStart(2, '0');
      const dateString = `${y}-${m}-${dayPad}`;

      const dayOfWeek = dateObj.getDay();
      days.push({
        dayNum: d,
        dateString,
        dayOfWeek,
        isWeekend: dayOfWeek === 0 || dayOfWeek === 6,
        isHoliday: !!holidaysDict[dateString],
        holidayName: holidaysDict[dateString] || '',
        isToday: dateString === todayStr,
      });
    }
    return days;
  }, [currentMonth, currentYear, now, holidaysDict]);

  const weeklyDays = useMemo(() => {
    const targetDate = activeSelected.dateObj;
    const day = targetDate.getDay();
    const diff = targetDate.getDate() - day + (day === 0 ? -6 : 1);
    const monday = new Date(targetDate);
    monday.setDate(diff);
    
    const week = [];
    for (let i = 0; i < 7; i++) {
      const current = new Date(monday);
      current.setDate(monday.getDate() + i);
      
      const y = current.getFullYear();
      const m = String(current.getMonth() + 1).padStart(2, '0');
      const dayPad = String(current.getDate()).padStart(2, '0');
      const dateString = `${y}-${m}-${dayPad}`;
      
      week.push({
        dayNum: current.getDate(),
        dateString,
        dayOfWeek: current.getDay(),
        isWeekend: current.getDay() === 0 || current.getDay() === 6,
        isHoliday: !!holidaysDict[dateString],
        holidayName: holidaysDict[dateString] || '',
        isToday: dateString === now.toISOString().split('T')[0],
      });
    }
    return week;
  }, [activeSelected.dateObj, holidaysDict, now]);

  const firstDayOffset = useMemo(() => {
    if (viewMode === 'mingguan') return 0;
    const firstDay = new Date(currentYear, currentMonth, 1).getDay();
    return firstDay === 0 ? 6 : firstDay - 1;
  }, [currentMonth, currentYear, viewMode]);

  if (!isOpen) return null;

  const prevStep = () => {
    if (viewMode === 'mingguan') {
      const prevWeek = new Date(activeSelected.dateObj);
      prevWeek.setDate(prevWeek.getDate() - 7);
      setCurrentMonth(prevWeek.getMonth());
      setCurrentYear(prevWeek.getFullYear());
      setSelectedDateStr(prevWeek.toISOString().split('T')[0]);
    } else {
      if (currentMonth === 0) {
        setCurrentMonth(11);
        setCurrentYear(currentYear - 1);
      } else {
        setCurrentMonth(currentMonth - 1);
      }
    }
  };

  const nextStep = () => {
    if (viewMode === 'mingguan') {
      const nextWeek = new Date(activeSelected.dateObj);
      nextWeek.setDate(nextWeek.getDate() + 7);
      setCurrentMonth(nextWeek.getMonth());
      setCurrentYear(nextWeek.getFullYear());
      setSelectedDateStr(nextWeek.toISOString().split('T')[0]);
    } else {
      if (currentMonth === 11) {
        setCurrentMonth(0);
        setCurrentYear(currentYear + 1);
      } else {
        setCurrentMonth(currentMonth + 1);
      }
    }
  };

  const resetToToday = () => {
    setCurrentMonth(now.getMonth());
    setCurrentYear(now.getFullYear());
    setSelectedDateStr(now.toISOString().split('T')[0]);
  };

  const formattedSelectedDate = () => {
    return activeSelected.dateObj.toLocaleDateString('id-ID', {
      weekday: 'long',
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
  };

  const toggleHoliday = async () => {
    if (activeSelected.isHoliday) {
      const result = await Swal.fire({
        title: 'Hapus Hari Libur?',
        text: `Hapus libur: ${activeSelected.holidayName}? Nomor surat pada tanggal ini akan kembali dialokasikan.`,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Ya, hapus!',
        cancelButtonText: 'Batal'
      });
      
      if (result.isConfirmed) {
        try {
          await deleteLibur(activeSelected.dateString);
          Swal.fire({ title: 'Terhapus!', text: 'Hari libur berhasil dihapus.', icon: 'success', toast: true, position: 'top-end', showConfirmButton: false, timer: 2000 });
        } catch (error) {
          Swal.fire('Gagal', 'Terjadi kesalahan saat menghapus hari libur.', 'error');
        }
      }
    } else {
      const { value: keterangan } = await Swal.fire({
        title: 'Tambah Hari Libur',
        text: 'Sistem nomor surat akan melompati tanggal libur secara otomatis.',
        input: 'text',
        inputLabel: 'Keterangan / Nama Libur',
        inputPlaceholder: 'Contoh: Cuti Bersama Idul Fitri',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        confirmButtonText: 'Simpan',
        inputValidator: (value) => {
          if (!value) return 'Keterangan tidak boleh kosong!';
        }
      });

      if (keterangan) {
        try {
          await addLibur({ tanggal: activeSelected.dateString, keterangan });
          Swal.fire({ title: 'Berhasil!', text: 'Hari libur ditambahkan.', icon: 'success', toast: true, position: 'top-end', showConfirmButton: false, timer: 2000 });
        } catch (error) {
          Swal.fire('Gagal', 'Terjadi kesalahan saat menambahkan hari libur.', 'error');
        }
      }
    }
  };

  const gridDays = viewMode === 'mingguan' ? weeklyDays : calendarDays;
  const currentMonthDisplay = viewMode === 'mingguan' ? activeSelected.dateObj.getMonth() : currentMonth;
  const currentYearDisplay = viewMode === 'mingguan' ? activeSelected.dateObj.getFullYear() : currentYear;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/40 backdrop-blur-md animate-fade-in"
      onClick={onClose}
    >
      <div
        className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-2xl rounded-[2.5rem] shadow-2xl shadow-red-900/20 border border-white/50 dark:border-gray-700/50 max-w-[22rem] w-full overflow-hidden flex flex-col font-sans max-h-[90vh] relative transition-all duration-300"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Vibe / Theme Background Decoration */}
        <div className="absolute top-0 left-0 w-full h-40 bg-gradient-to-b from-red-500/10 to-transparent pointer-events-none" />
        <div className="absolute -top-10 -right-10 w-48 h-48 bg-red-400/20 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col p-6 sm:p-7 h-full">
          {/* Header toggles */}
          <div className="flex items-center justify-between bg-black/5 dark:bg-white/5 rounded-2xl p-1 mb-6 border border-white/30 dark:border-gray-700/30 shadow-inner backdrop-blur-sm">
            <button 
              onClick={() => setViewMode('bulanan')}
              className={`flex-1 py-2 text-[13px] font-bold rounded-xl transition-all ${viewMode === 'bulanan' ? 'bg-white dark:bg-gray-700 shadow-sm text-gray-900 dark:text-white' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'}`}
            >
              Bulanan
            </button>
            <button 
              onClick={() => setViewMode('mingguan')}
              className={`flex-1 py-2 text-[13px] font-bold rounded-xl transition-all ${viewMode === 'mingguan' ? 'bg-white dark:bg-gray-700 shadow-sm text-gray-900 dark:text-white' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'}`}
            >
              Mingguan
            </button>
            <button onClick={onClose} className="w-9 h-9 flex items-center justify-center text-gray-400 hover:text-red-500 hover:bg-white/50 dark:hover:bg-gray-600/50 rounded-xl transition-all ml-1">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
          </div>

          {/* Month / Year Display */}
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-baseline gap-2">
              <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 dark:text-white tracking-tight">
                {monthsList[currentMonthDisplay]}
              </h2>
              <span className="text-2xl sm:text-3xl text-gray-400 dark:text-gray-500 font-light tracking-tight">{currentYearDisplay}</span>
            </div>
            <div className="flex flex-col gap-1.5">
              <button onClick={prevStep} className="w-7 h-7 rounded-full bg-white/60 dark:bg-gray-800/60 flex items-center justify-center text-gray-600 dark:text-gray-300 hover:bg-white hover:shadow-sm border border-gray-200/50 dark:border-gray-700/50 transition-all"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M15 19l-7-7 7-7"/></svg></button>
              <button onClick={nextStep} className="w-7 h-7 rounded-full bg-white/60 dark:bg-gray-800/60 flex items-center justify-center text-gray-600 dark:text-gray-300 hover:bg-white hover:shadow-sm border border-gray-200/50 dark:border-gray-700/50 transition-all"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M9 5l7 7-7 7"/></svg></button>
            </div>
          </div>

          {/* Days of week header */}
          <div className="grid grid-cols-7 mb-3">
            {['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'].map((day, idx) => (
              <div key={day} className={`text-center text-[11px] font-bold uppercase tracking-wider ${idx >= 5 ? 'text-red-400' : 'text-gray-400 dark:text-gray-500'}`}>
                {day}
              </div>
            ))}
          </div>

          {/* Grid */}
          <div className="grid grid-cols-7 gap-y-2 gap-x-1 relative">
            {/* Arced background highlight for today's week (simulated visual effect) */}
            <div className="absolute top-1/2 left-0 right-0 h-16 bg-white/40 dark:bg-gray-800/30 rounded-3xl -z-10 blur-md pointer-events-none" />

            {Array.from({ length: firstDayOffset }).map((_, i) => (
              <div key={`empty-${i}`} className="h-9 sm:h-10" />
            ))}

            {gridDays.map((dateObj) => {
              const isSelected = activeSelected.dateString === dateObj.dateString;
              return (
                <button
                  key={dateObj.dateString}
                  onClick={() => setSelectedDateStr(dateObj.dateString)}
                  title={dateObj.holidayName || (dateObj.isWeekend ? 'Akhir Pekan' : 'Hari Kerja')}
                  className={`h-9 sm:h-10 w-9 sm:w-10 mx-auto rounded-full flex items-center justify-center text-sm font-bold transition-all relative group
                    ${
                      dateObj.isToday
                        ? 'bg-red-500 text-white shadow-lg shadow-red-500/40 ring-4 ring-white/50 dark:ring-gray-900/50 scale-110 z-10'
                        : isSelected
                          ? 'bg-gray-800 dark:bg-gray-100 text-white dark:text-gray-900 shadow-md scale-105 z-10'
                          : dateObj.isWeekend || dateObj.isHoliday
                            ? 'text-red-400/80 hover:bg-white/60 dark:hover:bg-gray-800/60 hover:text-red-500'
                            : 'text-gray-700 dark:text-gray-300 hover:bg-white/80 dark:hover:bg-gray-700/60 hover:text-gray-900 dark:hover:text-white'
                    }
                  `}
                >
                  {dateObj.dayNum}
                  {/* Indicator dots */}
                  {!dateObj.isToday && !isSelected && dateObj.isHoliday && (
                    <span className="absolute bottom-1 w-1 h-1 rounded-full bg-red-400" />
                  )}
                  {!dateObj.isToday && !isSelected && !dateObj.isWeekend && !dateObj.isHoliday && (
                    <span className="absolute bottom-1 w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600 group-hover:bg-emerald-400 transition-colors" />
                  )}
                </button>
              );
            })}
          </div>

          {/* Bottom Actions */}
          <div className="mt-8 pt-5 border-t border-gray-200/40 dark:border-gray-700/40 flex items-center justify-between">
            <button onClick={resetToToday} className="flex items-center gap-1.5 text-xs font-bold text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-white transition-colors bg-white/30 dark:bg-gray-800/40 px-3.5 py-2 rounded-xl shadow-sm backdrop-blur-sm border border-white/50 dark:border-gray-700/50">
              <svg className="w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Hari Ini
            </button>
            
            {isAdmin && (
              <div className="flex items-center gap-2">
                <button 
                  onClick={toggleHoliday}
                  className={`flex items-center gap-2 text-xs font-bold text-white px-4 py-2 rounded-xl shadow-md transition-all border ${
                    activeSelected.isHoliday 
                      ? 'bg-gray-800 hover:bg-gray-700 shadow-gray-900/20 border-gray-700' 
                      : 'bg-red-500 hover:bg-red-600 shadow-red-500/20 border-red-400/50'
                  }`}
                >
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    {activeSelected.isHoliday ? (
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M20 12H4" />
                    ) : (
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 4v16m8-8H4" />
                    )}
                  </svg>
                  {activeSelected.isHoliday ? 'Hapus' : 'Tambah Libur'}
                </button>
              </div>
            )}
          </div>
          
          <div className="text-center mt-4">
               <p className="text-[13px] font-bold text-gray-800 dark:text-gray-100">{formattedSelectedDate()}</p>
               <p className={`text-[10px] font-medium truncate mt-0.5 ${activeSelected.isHoliday ? 'text-red-500' : 'text-gray-500 dark:text-gray-400'}`}>
                 {activeSelected.isHoliday ? `Libur: ${activeSelected.holidayName}` : activeSelected.isWeekend ? 'Libur Akhir Pekan' : 'Kerja SOP: 40 Nomor/Hari'}
               </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// legacy-persuratan/src/components/KalenderBulananModal.vue
<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-fade-in" @click.self="$emit('close')">
    <div class="bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-800 max-w-3xl w-full overflow-hidden flex flex-col font-sans">
      
      <!-- Header Modal (Clean Government Style: Red Theme) -->
      <div class="px-6 py-4 bg-gradient-to-r from-red-900 to-red-950 text-white flex items-center justify-between flex-shrink-0 border-b border-red-800">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-xl bg-red-600/20 border border-red-500/30 flex items-center justify-center text-red-400">
            <CalendarDaysIcon class="w-5 h-5" />
          </div>
          <div>
            <h3 class="text-base font-bold tracking-tight text-white">Kalender Kerja & Penomoran Harian SOP</h3>
            <p class="text-[11px] text-red-200/80 font-medium mt-0.5">Sekretariat DISKOMINFO • Blok Nomor 1 - 40 / Hari Kerja</p>
          </div>
        </div>
        <button @click="$emit('close')" class="w-8 h-8 rounded-lg bg-red-800/60 hover:bg-red-800 flex items-center justify-center text-red-100 transition-colors cursor-pointer">
          <XMarkIcon class="w-4 h-4" />
        </button>
      </div>

      <!-- Navigasi Bulan & Tahun -->
      <div class="px-6 py-3 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-3">
        <div class="flex items-center gap-2">
          <h4 class="text-lg font-bold text-slate-800 dark:text-slate-100 capitalize">
            {{ currentMonthName }} {{ currentYear }}
          </h4>
          <span class="px-2 py-0.5 rounded text-[11px] font-semibold bg-red-100 dark:bg-red-900/40 text-red-800 dark:text-red-300 border border-red-200 dark:border-red-800">
            SOP Kuota: 40 Nomor/Hari
          </span>
        </div>
        <div class="flex items-center gap-1.5">
          <button @click="prevMonth" class="px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 text-xs font-medium flex items-center gap-1 transition-colors shadow-2xs cursor-pointer">
            <ChevronLeftIcon class="w-3.5 h-3.5" />
            Sebelumnya
          </button>
          <button @click="resetToToday" class="px-3 py-1.5 rounded-lg bg-red-600 hover:bg-red-700 text-white text-xs font-semibold transition-colors shadow-2xs cursor-pointer">
            Hari Ini
          </button>
          <button @click="nextMonth" class="px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 text-xs font-medium flex items-center gap-1 transition-colors shadow-2xs cursor-pointer">
            Berikutnya
            <ChevronRightIcon class="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      <!-- Grid Hari dalam Seminggu -->
      <div class="p-6 pt-4 flex-1 overflow-y-auto">
        <div class="grid grid-cols-7 gap-2 mb-2 text-center">
          <div v-for="(day, idx) in daysOfWeek" :key="day" 
               :class="['text-[11px] font-bold py-1.5 rounded-lg border', idx >= 5 ? 'text-rose-600 bg-rose-50/60 dark:bg-rose-950/20 border-rose-100 dark:border-rose-900/30' : 'text-slate-600 dark:text-slate-300 bg-slate-100/80 dark:bg-slate-800 border-slate-200/60 dark:border-slate-700']">
            {{ day }}
          </div>
        </div>

        <!-- Grid Tanggal -->
        <div class="grid grid-cols-7 gap-2 text-center">
          <!-- Slot kosong sebelum tanggal 1 -->
          <div v-for="empty in firstDayOffset" :key="'empty-' + empty" class="h-16 rounded-xl bg-slate-50/40 dark:bg-slate-800/20 border border-transparent"></div>

          <!-- Hari dalam bulan -->
          <div v-for="dateObj in calendarDays" :key="dateObj.dateString"
               @click="selectedDate = dateObj"
               :class="[
                 'h-16 p-2 rounded-xl border flex flex-col justify-between transition-all cursor-pointer select-none relative group',
                 dateObj.isToday ? 'ring-2 ring-red-600 bg-red-50/80 dark:bg-red-900/30 border-red-500 font-bold shadow-sm' : '',
                 !dateObj.isToday && selectedDate?.dateString === dateObj.dateString ? 'bg-slate-100 dark:bg-slate-800 border-slate-400 dark:border-slate-500 shadow-2xs' : '',
                 !dateObj.isToday && dateObj.isWeekend ? 'bg-slate-50/80 dark:bg-slate-900/40 border-slate-100 dark:border-slate-800/80 text-slate-400 dark:text-slate-500' : '',
                 !dateObj.isToday && !dateObj.isWeekend && dateObj.isHoliday ? 'bg-amber-50/70 dark:bg-amber-950/20 border-amber-200/80 dark:border-amber-800/60 text-amber-800 dark:text-amber-300' : '',
                 !dateObj.isToday && !dateObj.isWeekend && !dateObj.isHoliday ? 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-red-400 dark:hover:border-red-600 text-slate-800 dark:text-slate-200 shadow-2xs' : ''
               ]">
            <!-- Nomor Tanggal & Indikator Titik -->
            <div class="flex items-center justify-between w-full">
              <span :class="['text-sm w-6 h-6 rounded-md flex items-center justify-center font-bold', dateObj.isToday ? 'bg-red-600 text-white' : '']">
                {{ dateObj.dayNum }}
              </span>
              <span v-if="dateObj.isHoliday" class="w-2 h-2 rounded-full bg-amber-500" title="Hari Libur Nasional"></span>
              <span v-else-if="dateObj.isWeekend" class="w-1.5 h-1.5 rounded-full bg-slate-300 dark:bg-slate-600" title="Akhir Pekan"></span>
              <span v-else class="w-2 h-2 rounded-full bg-emerald-500" title="Hari Kerja SOP (Aktif)"></span>
            </div>

            <!-- Mini Label (Clean) -->
            <div class="text-[10px] leading-tight truncate px-0.5 text-left font-medium">
              <span v-if="dateObj.isToday" class="text-red-700 dark:text-red-400 font-bold block">Hari Ini</span>
              <span v-else-if="dateObj.isHoliday" class="text-amber-700 dark:text-amber-400 truncate block">{{ dateObj.holidayName }}</span>
              <span v-else-if="dateObj.isWeekend" class="text-slate-400 dark:text-slate-500 block">Libur</span>
              <span v-else class="text-emerald-700 dark:text-emerald-400 font-semibold block">Hari Kerja</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Keterangan Warna / Legenda & Detail Hari -->
      <div class="px-6 py-3.5 bg-slate-50 dark:bg-slate-800/80 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-3 flex-shrink-0">
        <div class="flex items-center gap-3">
          <div :class="['w-9 h-9 rounded-lg flex items-center justify-center text-white font-bold text-base shadow-2xs', selectedDate?.isHoliday ? 'bg-amber-600' : (selectedDate?.isWeekend ? 'bg-slate-400' : 'bg-red-600')]">
            {{ selectedDate?.dayNum || '13' }}
          </div>
          <div>
            <h5 class="text-xs font-bold text-slate-800 dark:text-slate-100 leading-tight">
              {{ selectedDateFormatted }}
            </h5>
            <p class="text-[11px] font-medium mt-0.5" :class="selectedDate?.isHoliday ? 'text-amber-700 dark:text-amber-300' : (selectedDate?.isWeekend ? 'text-slate-500' : 'text-emerald-700 dark:text-emerald-400')">
              <span v-if="selectedDate?.isHoliday">🌴 Libur Nasional: {{ selectedDate?.holidayName }}</span>
              <span v-else-if="selectedDate?.isWeekend">🏖️ Libur Akhir Pekan (Sabtu/Minggu)</span>
              <span v-else>Hari Kerja SOP • Kuota 40 Nomor Surat (1 - 40 • Suffix A-Z)</span>
            </p>
          </div>
        </div>
        <div class="flex items-center gap-3 text-[11px] text-slate-500 dark:text-slate-400">
          <span class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-emerald-500 inline-block"></span>Hari Kerja</span>
          <span class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-amber-500 inline-block"></span>Libur Nasional</span>
          <span class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-slate-300 dark:bg-slate-600 inline-block"></span>Akhir Pekan</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { CalendarDaysIcon, XMarkIcon, ChevronLeftIcon, ChevronRightIcon } from '@heroicons/vue/24/outline'

const emit = defineEmits(['close'])

const now = new Date()
const currentMonth = ref(now.getMonth())
const currentYear = ref(now.getFullYear())

const daysOfWeek = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']

// Daftar Libur Nasional Indonesia & Cuti Bersama 2026
const holidays2026 = {
  '2026-01-01': 'Tahun Baru 2026 Masehi',
  '2026-01-16': 'Isra Mikraj Nabi Muhammad SAW',
  '2026-02-16': 'Cuti Bersama Tahun Baru Imlek',
  '2026-02-17': 'Tahun Baru Imlek 2577 Kongzili',
  '2026-03-18': 'Cuti Bersama Hari Suci Nyepi',
  '2026-03-19': 'Hari Suci Nyepi (Tahun Baru Saka 1948)',
  '2026-03-20': 'Cuti Bersama Idul Fitri 1447 H',
  '2026-03-21': 'Hari Raya Idul Fitri 1447 Hijriah',
  '2026-03-22': 'Hari Raya Idul Fitri 1447 Hijriah',
  '2026-03-23': 'Cuti Bersama Idul Fitri 1447 H',
  '2026-03-24': 'Cuti Bersama Idul Fitri 1447 H',
  '2026-04-03': 'Wafat Yesus Kristus',
  '2026-04-05': 'Kebangkitan Yesus Kristus (Paskah)',
  '2026-05-01': 'Hari Buruh Internasional',
  '2026-05-14': 'Kenaikan Yesus Kristus',
  '2026-05-15': 'Cuti Bersama Kenaikan Yesus Kristus',
  '2026-05-27': 'Idul Adha 1447 Hijriah',
  '2026-05-28': 'Cuti Bersama Idul Adha 1447 H',
  '2026-05-31': 'Hari Raya Waisak 2570 BE',
  '2026-06-01': 'Hari Lahir Pancasila',
  '2026-06-16': '1 Muharram Tahun Baru Islam 1448 Hijriah',
  '2026-08-17': 'Proklamasi Kemerdekaan Republik Indonesia ke-81',
  '2026-08-25': 'Maulid Nabi Muhammad SAW',
  '2026-12-24': 'Cuti Bersama Hari Raya Natal',
  '2026-12-25': 'Hari Raya Natal'
}

const monthsList = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
]

const currentMonthName = computed(() => monthsList[currentMonth.value])

const firstDayOffset = computed(() => {
  const firstDay = new Date(currentYear.value, currentMonth.value, 1).getDay()
  return firstDay === 0 ? 6 : firstDay - 1
})

const calendarDays = computed(() => {
  const daysInMonth = new Date(currentYear.value, currentMonth.value + 1, 0).getDate()
  const days = []
  const todayStr = now.toISOString().split('T')[0]

  for (let d = 1; d <= daysInMonth; d++) {
    const dateObj = new Date(currentYear.value, currentMonth.value, d)
    const y = dateObj.getFullYear()
    const m = String(dateObj.getMonth() + 1).padStart(2, '0')
    const dayPad = String(d).padStart(2, '0')
    const dateString = `${y}-${m}-${dayPad}`

    const dayOfWeek = dateObj.getDay()
    const isWeekend = (dayOfWeek === 0 || dayOfWeek === 6)
    const isHoliday = !!holidays2026[dateString]
    const isToday = (dateString === todayStr)

    days.push({
      dayNum: d,
      dateString,
      dayOfWeek,
      isWeekend,
      isHoliday,
      holidayName: holidays2026[dateString] || '',
      isToday
    })
  }
  return days
})

const selectedDate = ref(calendarDays.value.find(d => d.isToday) || calendarDays.value[0])

const selectedDateFormatted = computed(() => {
  if (!selectedDate.value) return ''
  const [y, m, d] = selectedDate.value.dateString.split('-')
  const dateObj = new Date(y, parseInt(m) - 1, d)
  return dateObj.toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
})

const prevMonth = () => {
  if (currentMonth.value === 0) {
    currentMonth.value = 11
    currentYear.value--
  } else {
    currentMonth.value--
  }
}

const nextMonth = () => {
  if (currentMonth.value === 11) {
    currentMonth.value = 0
    currentYear.value++
  } else {
    currentMonth.value++
  }
}

const resetToToday = () => {
  currentMonth.value = now.getMonth()
  currentYear.value = now.getFullYear()
  selectedDate.value = calendarDays.value.find(d => d.isToday) || calendarDays.value[0]
}
</script>
